baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Filip Poplewski'
theme = ["hugo-embed-pdf-shortcode", "terminal"]
enableInlineShortcodes = true

[params]
  contentTypeName = "posts"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
